apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql
  namespace: expense
  #these labels are deployment related labels
  labels:
    component: mysql
    project: expense
    tier: db
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      component: mysql
      project: expense
      tier: db
  # these labels are related to pod defination
  template:
    metadata:
      labels:
        component: mysql
        project: expense
        tier: db
    spec:
      containers:
      - name: mysql
        image: lingannaj/mysql:{{ .Values.deployment.imageVersion }}