apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector: # using the selector option to connect the pod wit same labels service create the cluster ip
    component: mysql
    project: expense
    tier: db
  ports:
  - protocol: TCP
    port: 3306 #service-port
    targetPort: 3306 #target-port