apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector: # using the selector option to connect the pod wit same labels service create the cluster ip
    component: frontend
    project: expense
    tier: web
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: {{ .Values.configmap.port }} #target-port