apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend
  namespace: expense
  #these labels are deployment related labels
  labels:
    component: backend
    project: expense
    tier: app
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      component: backend
      project: expense
      tier: app
  # these labels are related to pod defination
  template:
    metadata:
      labels:
        component: backend
        project: expense
        tier: app
    spec:
      containers:
      - name: backend
        image: lingannaj/backend:{{ .Values.deployment.imageVersion }}
        envFrom:
        - configMapRef:
            name: backend
        