apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector: # using the selector option to connect the pod wit same labels service create the cluster ip
    component: backend
    project: expense
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #target-port